enum NavigationEnum {
  HANDLE_PROJECTS,
  HANDLE_USERS,
}
enum ProjectActionsEnum {
  DELETE_UNITS,//0
  EDIT_UNIT,//1
  EDIT_PROJECT,//2
  ADD_MEETINGS,//3
  EDIT_NOTES,//4
  EDIT_GROUP,//5
  CREATE_UNITS,//6
  CREATE_PROJECT,//7
  UNREGISTER_STUDENT,//8
  DELETE_PROJECT,//9
}

enum Roles {
  STUDENT,
  TEACHER,
  ADMINISTRATOR,
}
